kanta = float(input("Anna suorakulmion kanta: "))
korkeus = float(input("Anna suorakulmion korkeus: "))
piiri = (2*kanta+korkeus)
pintaala = (kanta*korkeus)
print("Suorakulmion piiri on: "+ str(piiri))
print("Suorakulmion pinta-ala: "+ str(pintaala))